version: '3.9'

services:
    nginx:
        image: nginx:latest
        container_name: dpp_nginx
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build: ./docker/php
        container_name: dpp_php
        volumes:
            - ./:/var/www
